services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.4
    command: ["start-dev", "--http-port=8080", "--import-realm"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    volumes:
      - ./realm:/opt/keycloak/data/import
